"  Author: George Bellos <georgebellos@me.com>
"  Source: http://github.com/georgebellos/dotfiles/tree/master/vim
" setup ----------------------------------------------------------------- {{{
set nocompatible " be iMproved
filetype off     " required!
set rtp+=~/.vim/bundle/vundle/ " path to install plugins

call vundle#rc()
Plugin 'gmarik/vundle'

" Use local bundles if available
if filereadable(expand("~/.vimrc.bundles.local"))
  source ~/.vimrc.bundles.local
endif

set shell=$SHELL

" }}}
" Plugins via Vundle --------------------------------------------------- {{{
" Git, Buffers, Undo, Fuzzy file finder-----------------------{{{

"Git on your Vim
Plugin 'tpope/vim-fugitive'

" Create gists
if executable('curl')
  "Plugin 'mattn/gist-vim'
endif

"--------------------------------
" Navigation - windows - Buffers
"--------------------------------

" Sidebar for files
Plugin 'scrooloose/nerdtree'

" Fuzzy file finder
Plugin 'kien/ctrlp.vim'

" Ctrlp extension - replacement for tags"
Plugin 'tacahiroy/ctrlp-funky'

" CtrlP extension for fuzzy-search in tag matches
Plugin 'ivalkeen/vim-ctrlp-tjump'

" Undo managment
Plugin 'sjl/gundo.vim'

" Manage Buffers
Plugin 'jeetsukumaran/vim-buffergator'
"Plugin 'niklasb/bufkill.vim'

" Tagbar
if executable('ctags')
  Plugin 'majutsushi/tagbar'
endif

" vim + tmux + iterm
" Vitality restores the FocusLost and FocusGained autocommand functionality. Now Vim can save when iTerm 2 loses focus, even if it's inside tmux!
" It also handles switching the cursor to a bar shaped one when in insert mode, and restoring it when not.
Plugin 'sjl/vitality.vim'

" almost a shell
"Plugin 'ervandew/screen'

" Zoom windows
"Plugin 'vim-scripts/ZoomWin'

" Session Managment
" Plugin 'xolox/vim-session'
" Plugin 'xolox/vim-misc'
" Plugin 'xolox/vim-shell'
Plugin 'mhinz/vim-startify'


" Advanced search with ack -> https://github.com/mileszs/ack.vim
if executable('ack')
  Plugin 'mileszs/ack.vim'
endif

" line up text with tabular
"Plugin 'godlygeek/tabular'
" }}}
" Editing - Automating--------------------------------------------------{{{

" Syntax checking
Plugin 'scrooloose/syntastic'

" Enhaced motions
Plugin 'Lokaltog/vim-easymotion'

" Delete,change,add surroundings(parentheis, brackets, etc)
Plugin 'tpope/vim-surround'

" end certain structures automatically
Plugin 'tpope/vim-endwise'

" Complementary pairs of mappings
Plugin 'tpope/vim-unimpaired'

" Select and operate on various types of objects
"  provides a text object based on indentation level
Plugin 'vim-indent-object'

" provides text object for function arguments
Plugin 'vim-scripts/argtextobj.vim'

" provides a text object to move by words within a camel or snake-cased word
Plugin 'bkad/CamelCaseMotion'

" Commnets
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-commentary'
"Plugin 'tomtom/tcomment_vim'

" Enhaced Repeat Command
Plugin 'tpope/vim-repeat'

" Remaps the <Space> key to act as a clever key to repeat motions.
"Plugin 'spiiph/vim-space'

" Extended matching with %
Plugin 'edsono/vim-matchit'

" Plugin 'Raimondi/delimitMate'
"imap <C-c> <CR><Esc>O

" Support writing user-defined text objects
Plugin 'kana/vim-textobj-user'

" Readline mappings insert, command mode
Plugin 'tpope/vim-rsi'

Plugin 'tpope/vim-dispatch'

" autocompletion
"Plugin 'Shougo/neocomplcache.vim'
"Plugin 'othree/vim-autocomplpop'
"Plugin 'vim-scripts/L9'

Plugin 'ervandew/supertab'
"let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
let g:SuperTabDefaultCompletionType = "context"

"snippets files for various programming languages
Plugin 'honza/vim-snippets'

" snippets engine most popular oldest solution
Plugin 'garbas/vim-snipmate'

" problems on start but this is a better engine
"Plugin 'SirVer/ultisnips'

" problems not working
"Plugin 'MarcWeber/ultisnips'

"let g:UltiSnipsUsePythonVersion = 2
"let g:UltiSnipsExpandTrigger="<tab>"
"let g:UltiSnipsJumpForwardTrigger="<tab>"
"let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

"Plugin 'Shougo/neosnippet'

" interpret a file by function and cache file automatically
Plugin 'MarcWeber/vim-addon-mw-utils'

" Focusing - editing on a region
"Plugin 'chrisbra/NrrwRgn'

" Increase dates and times
Plugin 'tpope/vim-speeddating'

" Sudo gui
"Plugin 'gmarik/sudo-gui.vim'

Plugin 'tomtom/tlib_vim'

" Code Substitution
" Plugin 'AndrewRadev/switch.vim'

" shell support
Plugin 'tpope/vim-eunuch'

" Tmux support
Plugin 'benmills/vimux'

" switch panes with c-(hjkl)
Plugin 'christoomey/vim-tmux-navigator'

"}}}
" Ruby development support----------------------------------------------- {{{

"highlighting-warnings-checking
Plugin 'vim-ruby/vim-ruby'

" Ruby vim objects
Plugin 'nelstrom/vim-textobj-rubyblock'

" Execute ruby files in a buffer
Plugin 'henrik/vim-ruby-runner'

" Execute ruby code inline :dependent 'gem install rcodetools'
Plugin 't9md/vim-ruby-xmpfilter'

" Minitest syntax & completion
Plugin 'sunaku/vim-ruby-minitest'

" Run minitest with vimux
Plugin 'pgr0ss/vimux-ruby-test'
"
" Run ruby tests writtern with minitest via vimux and vroom
Plugin 'skalnik/vim-vroom'

" Ruby Documentation via ri tool
"Plugin 'danchoi/ri.vim'

" Ruby local documentation via browser
Plugin 'lucapette/vim-ruby-doc'

" Run ruby tests written with rspec
Plugin 'thoughtbot/vim-rspec'

"Plugin 'skwp/vim-ruby-conque'

" Debugger support
"Plugin 'astashov/vim-ruby-debugger'

" Refactoring Ruby
 "Plugin 'ecomba/vim-ruby-refactoring'

" similar with rails.vim but for all ruby projects
Plugin 'tpope/vim-rake'

" Rails development support
"--------------------------

"navigate, syntax, commands
Plugin 'tpope/vim-rails'

"tail command
Plugin  'vim-scripts/TailMinusF'

" :Rpreview
:command! -bar -nargs=1 OpenURL :!open <args>


" }}}
"Elixir & Erlang development support {{{

" Elixir syntax,indent,compiler,filetype
Plugin 'elixir-lang/vim-elixir'

" mix tasks from vim
Plugin 'mattonrails/vim-mix'

" Erlang http://blog.erlware.org/2013/09/09/how-to-use-vim-for-erlang-development/
"Plugin 'oscarh/vimerl'

"more ...
" https://github.com/vim-erlang
"replace above identation
"Plugin 'hcs42/vim-erlang-runtime'

"}}}
"Clojure development support {{{

" clojure repl,comletion, documentation, code navigation
Plugin 'tpope/vim-fireplace'

"Because the class path is oh-so-expensive to retrieve, "classpath.vim caches it
"in ~/.cache/vim/classpath. The cache is expired when the timestamp on project.
" "clj or pom.xml changes.
Plugin 'tpope/vim-classpath'

Plugin 'tpope/vim-leiningen'
Plugin 'tpope/vim-projectionist'

" syntax, indent, and filetype settings for Clojure and ClojureScript files.
Plugin 'guns/vim-clojure-static'

Plugin 'guns/vim-clojure-highlight'

"colored parenthesis, brackets etc
Plugin 'kien/rainbow_parentheses.vim'

"clojure folding
Plugin 'gberenfield/cljfold.vim'
let g:clojure_foldwords = "def,ns,deftest,"

Plugin 'guns/paredit'
"}}}
" coffeescript & Javascript development " support--------------------------{{{
"https://github.com/joyent/node/wiki/Vim-Plugins

" Syntax
Plugin 'kchmck/vim-coffee-script'

" Browse code base
"Plugin 'clvv/a.vim'

" Literate programming support:syntax highlighting and indentation
Plugin 'mintplant/vim-literate-coffeescript'

" coffee text objects
Plugin 'AndrewRadev/coffee_tools.vim'

" Syntax highlighting for json
Plugin 'leshill/vim-json'

" Syntax
Plugin 'pangloss/vim-javascript'

"Enhanced JavaScript Syntax
Plugin 'jelera/vim-javascript-syntax'

"mustache and handlebars mode for vim
Plugin 'mustache/vim-mode'

" documentation etc
"Plugin 'marijnh/tern_for_vim'

"Vim syntax file to add some colorations for jQuery keywords and css selector
Plugin 'itspriddle/vim-jquery'

"Browse jquery docs api
Plugin 'lucapette/vim-jquery-doc'

Plugin 'taxilian/vim-web-indent'
"}}}
" Html/Css development support "  -------------------------------------------------- {{{

"sass syntax highlighting
Plugin 'cakebaker/scss-syntax.vim'

"markdown support
"Plugin 'plasticboy/vim-markdown'
"Plugin 'tpope/vim-markdown'
Plugin 'nelstrom/vim-markdown-folding'

"liquid templates support
Plugin 'tpope/vim-liquid'

"haml templates support
"Plugin 'tpope/vim-haml'

"advanced abrevvations etc more here http://emmet.io
"Plugin 'mattn/emmet-vim'

"SASS and Compass Snippets for Vim's Snipmate Plugin
Plugin 'kwaledesign/scss-snippets'

"hexadecimal CSS colorcodes with their real color
Plugin 'skammer/vim-css-color'
"Plugin 'ap/vim-css-color' "slow down my rails files

"checkout

"Plugin 'vim-scripts/HTML-AutoCloseTag'
"Plugin 'rstacruz/sparkup', {'rtp': 'vim'}
"Plugin 'ChrisYip/Better-CSS-Syntax-for-Vim'
"Plugin 'hallison/vim-markdown'

"}}}
" Vim Interface---------------------------------------------------------- {{{

" Fancy status line
"Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
"Plugin 'maciakl/vim-neatstatus'
Plugin 'bling/vim-airline'

"Keep layout
"Plugin 'moll/vim-bbye'

" Diffs signs
" disable on start and then toggle on off
"Plugin 'tomtom/quickfixsigns_vim'

" problem when saving. it stops for a second to update gutter find a way to
" disable this"
"Plugin 'airblade/vim-gitgutter'
"let g:gitgutter_enabled = 0
"let g:gitgutter_realtime = 0
"let g:gitgutter_eager = 0
"let g:gitgutter_escape_grep = 1
"nmap <leader>st ::GitGutterToggle<cr>


Plugin 'mhinz/vim-signify'
"works with other vcs but it make slow when you open a file, it can show color
"inline not just signs - with these setting it is not slow
let g:signify_vcs_list=['git']
let g:signify_skip_filetype = { 'txt': 1 }
let g:signify_disable_by_default = 1
let g:signify_mapping_toggle = '<leader>st'
let g:signify_mapping_next_hunk = '<leader>gj'
let g:signify_mapping_prev_hunk = '<leader>gk'

" handle colors easier -> https://github.com/Rykka/colorv.vim
"Plugin 'Rykka/colorv.vim'

" needed for fetching schemes online.
"Plugin 'mattn/webapi-vim'

" visual indent
"Plugin 'nathanaelkane/vim-indent-guides'

" Colorschemes
Plugin 'altercation/vim-colors-solarized'
"Plugin 'wgibbs/vim-irblack'
"Plugin 'sjl/badwolf'
"Plugin 'tomasr/molokai'
"Plugin 'jpo/vim-railscasts-theme'
"Plugin 'spf13/vim-colors'
"Plugin 'flazz/vim-colorschemes'
"Plugin 'eddsteel/vim-lanai'
"Plugin 'noahfrederick/vim-hemisu'

" }}}
"Productivity ----------------------------------------------{{{
"Plugin 'amdt/sunset'
"Plugin 'Dinduks/vim-holylight'
"Plugin 'chrisbra/Recover.vim'
Plugin 'tangledhelix/vim-octopress'
"Plugin 'beloglazov/vim-online-thesaurus'
Plugin 'itchyny/thumbnail.vim'
Plugin 'chrisbra/DistractFree'

 "Documention via dash
"Plugin 'rizzatti/dash.vim'
"Plugin 'rizzatti/funcoo.vim'
" }}}
" Other Languages Support------------------------------------------------ {{{
"Haskell
Plugin 'wlangstroth/vim-haskell'
" }}}
" }}}
" Vim configuration ------------------------------------------------------- {{{
" Directories {{{
set backup
set backupdir=~/.vim/dirs/backup
set directory=~/.vim/dirs/temp

set history=1000                " Store a ton of history (default is 20)
set noswapfile

if has('persistent_undo')
  set undofile                "so is persistent undo ...
  set undolevels=1000         "maximum number of changes that can be undone
  set undoreload=10000        "maximum number lines to save for undo on a buffer reload
endif

if exists("&undodir")
  set undodir=~/.vim/dirs/undo
endif

"Thesaurus Setup
set thesaurus+=~/.vim/thesaurus/ruby.txt
set thesaurus+=~/.vim/thesaurus/roget13a.txt

"}}}
" Interface - gui ----------------------------------------------------- {{{

" ---------------
"  Colorscheme
" ---------------

set guifont=Monaco\ for\ Powerline:h12
if has('gui_running')
  color solarized
else
  color solarized
endif


set background=light
set antialias                     " MacVim: smooth fonts.
set synmaxcol=120                 " Prevent lag on long lines (default: 3000)
set ruler                         " Ruler on
set nu                            " Line numbers on
set wrap
set linespace=0
"Color the 80th column differently
"if exists('+colorcolumn')
  "set colorcolumn=80
"endif

"-------------------------------
" Windows, Toolbars and cursor
"-------------------------------

if has('gui_macvim')
  " Use option (alt) as meta key.
  set macmeta

  if has("gui_running")             " Hide Toolbar in MacVim
    set guioptions=egmrt
  endif
endif

set guioptions-=T                 " Hide toolbar.
set guioptions-=L                 " Hide left scrolbar.
set guioptions-=r                 " Hide right scrolbar.

"----------------------
"      Status Bar
"----------------------

set laststatus=2                  " Always show the statusline
set cmdheight=1                   " Make the command area two lines high



" Cursor and cursorline settings
set gcr=n:blinkon0                         " no blinking cursor in normal mode
set gcr=a:blinkon0                         " stop blinking cursor in all modes
set cursorline                             " Show cursor line
highlight lCursor guifg=white guibg=red    " different color cursor for greek key map

" Use a bar-shaped cursor for insert mode, even through tmux.
" tmux cursor bar shaped cursor for insert mode
" if exists('$TMUX')
"   let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
"   let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
" else
"   let &t_SI = "\<Esc>]50;CursorShape=1\x7"
"   let &t_EI = "\<Esc>]50;CursorShape=0\x7"
" endif


" Visual
set showmatch                     " Show matching brackets.
set scrolloff=5                   " show 3 lines of context around the cursor.
set virtualedit=onemore           " allow for cursor beyond last character

" Disable tooltips for hovering keywords in Vim
if exists('+ballooneval')
  " This doesn't seem to stop tooltips for Ruby files
  set noballooneval
  " 100 second delay seems to be the only way to disable the tooltips
  set balloondelay=100000
endif

" Sounds
set noerrorbells
set novisualbell
set t_vb=

" Mouse
set mousehide  " Hide mouse after chars typed
set mouse=a  " Mouse in all modes


" }}}
"   Behaviors {{{

filetype plugin indent on         " Automatically detect file types.
set encoding=utf-8
syntax enable
set autoread                      " Automatically reload changes if detected
set cf                            " Enable error files & error jumping.
set clipboard+=unnamed            " Yanks go on clipboard instead.
set autowrite                     " Writes on make/shell commands
set formatoptions=crql
set iskeyword+=$,@                " Add extra characters that are valid parts of variables
set showcmd

set hidden                        " allow buffer switching without saving
set noea                          " dont resize bufffers automatically
set isfname+=32    " have a space (ASCII 32) considered as a valid character for a file name

au FocusLost * silent! wa         " save when you lose focus

"Folding
set foldmethod=indent
set foldlevelstart=99             " Remove folds when you open a file

"folding for vimscript files
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

set nrformats-=octal  "numbers that start with a zero will be considered to be octal
set shiftround
set fileformats+=mac

" }}}
" Text Format {{{
" ---------------
set nowrap                        " don't wrap lines
"set autoindent                    " indent at the same level of the previous line
set tabstop=2
set backspace=2                   " Delete everything with backspace
"set shiftwidth=2                  " Tabs under smart indent
"set cindent
set smarttab

" ---------------
" Whitespace
" ---------------

set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode

if exists("g:enable_mvim_shift_arrow")
  let macvim_hig_shift_movement = 1 " mvim shift-arrow-keys
endif

"set pastetoggle=<F12>           " pastetoggle (sane indentation on pastes)

" ---------------
" List chars
" ---------------

set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
" Remove trailing whitespaces and ^M chars
autocmd FileType ruby,objc,objcpp,coffee,javascript,scheme,clojure,c,scss,css,html,eruby,markdown,elixir,haskell,erlang,vimrc,cpp,java,python,xml,yaml,text,txt autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\\s\\+$","","")'))

" }}}
"   Searching  & Completion ----------------------------------------------------- {{{

set hlsearch                      " highlight matches
set incsearch                     " incremental searching
set ignorecase                    " searches are case insensitive...
set smartcase                     " ... unless they contain at least one capital letter
set wildignore+=*.o,*.obj,*.exe,*.so,*.dll,*.pyc,.svn,.hg,.bzr,.git,.sass-cache,*.class,*.scssc

set complete=.,w,b,u,t,i,U,s,k
set completeopt=menu,preview


" -----------------
" Wildmenu settings
" -----------------

set wildmenu                      " Turn on WiLd menu

set showmode                     "shomode and wild menu

set wildmode=list:longest,list:full  " more results not just one

" Disable output and VCS files
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem

" Disable archive files
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz

" Ignore bundler and sass cache
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*

" Ignore temp and backup files
set wildignore+=*.swp,*~,._*

" Ignore OSX .ds_store files
set wildignore+=*.DS_Store$


"--------------------
" general
"--------------------

autocmd FileType xml setlocal macmeta              " required for MacVim
autocmd FileType xml imap <buffer> <M-D-.> </<C-X><C-O>

"Fix terminal timeout when pressing escape
"When you’re pressing Escape to leave insert mode in the terminal, it will by default take a second or another keystroke to leave insert mode completely and update the statusline. If you find this annoying, you can add the following snippet to your vimrc to escape insert mode immediately:

if ! has('gui_running')
  set ttimeoutlen=10
  augroup FastEscape
    autocmd!
    au InsertEnter * set timeoutlen=0
    au InsertLeave * set timeoutlen=1000
  augroup END
endif

" }}}
" Mapping ------------------------------------------------------------ {{{

"The default leader is '\', but many people prefer ',' as it's in a standard location
let mapleader=","

"next buffer via leader .
map <leader>. :bn<cr>

" preview markdown files with Marked app
:nnoremap <leader>om :silent !open -a Marked.app '%:p'<cr>

" open current directory in iterm
:nnoremap <leader>it :!open -a iTerm .<cr>
:nnoremap <leader>if :!open .<cr>
:nnoremap <leader>im :!open -a Macvim .<cr>

" edit .vimrc file
:nnoremap <leader>ev :edit $MYVIMRC<cr>
:nnoremap <leader>eg :vsplit $MYGVIMRC<cr>
:nnoremap <leader>et :vsplit ~/.tmux.conf<cr>
:nnoremap <leader>ez :vsplit ~/.zshrc<cr>
:nnoremap <leader>en :vsplit ~/.zshenv<cr>

" source .vimrc
:nnoremap <leader>sv :source $MYVIMRC<cr>
:nnoremap <leader>sg :source $MYGVIMRC<cr>

" insert new line below and above without entering insert mode
nnoremap <M-j> m`o<Esc>``
nnoremap <M-k> m`O<Esc>``

" greek support via keymap
map <leader>km :set keymap=greek_utf-8<CR>
map <leader>kn :set keymap=<CR>


" change directory to documents
:nnoremap <leader>ia :cd ~/workspace/iawriter<cr>

" change colorscheme to iawriter
:nnoremap <leader>ic :colorscheme iawriter<cr>
:nnoremap <leader>iu :colorscheme ulysses<cr>

" open explorer
nmap ,, :e.<CR>

map <leader>fi :setlocal foldmethod=indent<cr>
map <leader>fs :setlocal foldmethod=syntax<cr>
map <leader>fm :setlocal foldmethod=marker<cr>

"-------------------------------
" Janus Mappings
"-------------------------------

"" General Mappings (Normal, Visual, Operator-pending)

" Toggle paste mode
nmap <silent> <F4> :set invpaste<CR>:set paste?<CR>
imap <silent> <F4> <ESC>:set invpaste<CR>:set paste?<CR>

" format the entire file
nmap <leader>fef ggVG=

" upper/lower word
noremap <leader>u mQviwU`Q
noremap <leader>l mQviwu`Q

" upper/lower first char of word
noremap <leader>U mQgewvU`Q
noremap <leader>L mQgewvu`Q

" cd to the directory containing the file in the buffer
nmap <silent> <leader>cd :lcd %:h<CR>

" Create the directory containing the file in the buffer
"nmap <silent> <leader>md :!mkdir -p %:p:h<CR>

" Some helpers to edit mode
" http://vimcasts.org/e/14
cnoremap %% <C-R>=expand('%:h').'/'<cr>
nmap <leader>ew :e <C-R>=expand('%:h').'/'<cr>
nmap <leader>es :sp <C-R>=expand('%:h').'/'<cr>
"nmap <leader>ev :vsp <C-R>=expand('%:h').'/'<cr>
nmap <leader>et :tabe <C-R>=expand('%:h').'/'<cr>

" Swap two words
nmap <silent> gw :s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR>`'

" Underline the current line with '='
"nmap <silent> <leader>uL :t.\|s/./=/g\|:nohls<cr>
nmap <silent> <leader>uL :t.<CR>Vr=

" Underline the current line with '-'
"nmap <silent> <leader>ul :t.\|s/./-/g\|:nohls<cr>
nmap <silent> <leader>ul :t.<CR>Vr-

" set text wrapping toggles
nmap <silent> <leader>tw :set invwrap<CR>:set wrap?<CR>

" find merge conflict markers
nmap <silent> <leader>fc <ESC>/\v^[<=>]{7}( .*\|$)<CR>

" Map the arrow keys to be based on display lines, not physical lines
map <Down> gj
map <Up> gk

" Toggle hlsearch with <leader>hs
nmap <leader>hs :set hlsearch! hlsearch?<CR>

" Adjust viewports to the same size
map <Leader>= <C-w>=

if has("gui_macvim") && has("gui_running")
  " Map command-[ and command-] to indenting or outdenting
  " while keeping the original selection in visual mode
  vmap <D-]> >gv
  vmap <D-[> <gv

  nmap <D-]> >>
  nmap <D-[> <<

  omap <D-]> >>
  omap <D-[> <<

  imap <D-]> <Esc>>>i
  imap <D-[> <Esc><<i

  " Bubble single lines
  nmap <D-Up> [e
  nmap <D-Down> ]e
  nmap <D-k> [e
  nmap <D-j> ]e

  " Bubble multiple lines
  vmap <D-Down> ]egv
  vmap <D-Up> [egv
  vmap <D-k> [egv
  vmap <D-j> ]egv

  " Map Command-# to switch tabs
  map  <D-0> 0gt
  imap <D-0> <Esc>0gt
  map  <D-1> 1gt
  imap <D-1> <Esc>1gt
  map  <D-2> 2gt
  imap <D-2> <Esc>2gt
  map  <D-3> 3gt
  imap <D-3> <Esc>3gt
  map  <D-4> 4gt
  imap <D-4> <Esc>4gt
  map  <D-5> 5gt
  imap <D-5> <Esc>5gt
  map  <D-6> 6gt
  imap <D-6> <Esc>6gt
  map  <D-7> 7gt
  imap <D-7> <Esc>7gt
  map  <D-8> 8gt
  imap <D-8> <Esc>8gt
  map  <D-9> 9gt
  imap <D-9> <Esc>9gt
else

  " Map command-[ and command-] to indenting or outdenting
  " while keeping the original selection in visual mode
  vmap <A-]> >gv
  vmap <A-[> <gv

  nmap <A-]> >>
  nmap <A-[> <<

  omap <A-]> >>
  omap <A-[> <<

  imap <A-]> <Esc>>>i
  imap <A-[> <Esc><<i

  " Make shift-insert work like in Xterm
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>

  " Map Control-# to switch tabs
  map  <C-0> 0gt
  imap <C-0> <Esc>0gt
  map  <C-1> 1gt
  imap <C-1> <Esc>1gt
  map  <C-2> 2gt
  imap <C-2> <Esc>2gt
  map  <C-3> 3gt
  imap <C-3> <Esc>3gt
  map  <C-4> 4gt
  imap <C-4> <Esc>4gt
  map  <C-5> 5gt
  imap <C-5> <Esc>5gt
  map  <C-6> 6gt
  imap <C-6> <Esc>6gt
  map  <C-7> 7gt
  imap <C-7> <Esc>7gt
  map  <C-8> 8gt
  imap <C-8> <Esc>8gt
  map  <C-9> 9gt
  imap <C-9> <Esc>9gt
endif

" Insert the current directory into a command-line path
cnoremap <expr> <C-P> getcmdline()[getcmdpos()-2] ==# ' ' ? expand('%:p:h') : "\<C-P>"

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

"insert new live above(emac binding)
imap <M-o> <Esc>o

"--------------------
"" File types
"--------------------

filetype plugin indent on " Turn on filetype plugins (:help filetype-plugin)

if has("autocmd")
  " In Makefiles, use real tabs, not tabs expanded to spaces
  au FileType make setlocal noexpandtab

  " This actually might be confusing, but the plugin +ruby+ already does
  " this, so we want to do it only if the plugin +ruby+ is disabled for
  " some reason
  " Set the Ruby filetype for a number of common Ruby files without .rb
  au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,Procfile,config.ru,*.rake} set ft=ruby
  "endif

  " Make sure all mardown files have the correct filetype set and setup wrapping
  "au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn,txt} setf markdown | call s:setupWrapping()

  " Treat JSON files like JavaScript
  au BufNewFile,BufRead *.json set ft=javascript

  " make Python follow PEP8 for whitespace ( http://www.python.org/dev/peps/pep-0008/ )
  "au FileType python setlocal softtabstop=4 tabstop=4 shiftwidth=4

  " Remember last location in file, but not for commit messages.
  " see :help last-position-jump
  au BufReadPost * if &filetype !~ '^git\c' && line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g`\"" | endif
  au BufRead,BufNewFile *.scss             set ft=scss.css

endif

"set filetypes like textmate
command! FR set filetype=ruby
command! FC set filetype=coffee
command! FCL set filetype=clojure
command! FJ set filetype=javascript
command! FO set filetype=objc
command! FH set filetype=haskell
command! FE set filetype=elixir
command! EL set filetype=erlang
command! FM set filetype=markdown
command! FN set filetype=


autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1


" Use <C-M> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-m> :nohlsearch<CR><C-L>
endif

" Toggle relative line number
function! NumberToggle()
  if(&relativenumber)
    set norelativenumber
    set number
  else
    "" Uncomment the following to display a '0' instead of the line number
    " set nonumber
    set relativenumber
  endif
endfunc

" Toggle folds with space
nnoremap <Space> za
vnoremap <Space> za

" Keep the cursor in place while joining lines
nnoremap J mzJ`z

" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv

" Same when jumping around
nnoremap g\; g\;zz
nnoremap g, g,zz
nnoremap <c-o> <c-o>zz

" Easier to type, and I never use the default behavior.
noremap H ^
noremap L $
vnoremap L g_

" toggles the quickfix window.
command! -bang -nargs=? QFix call QFixToggle(<bang>0)
function! QFixToggle(forced)
  if exists("g:qfix_win") && a:forced == 0
    cclose
  else
    execute "Copen!"
  endif
endfunction

" used to track the quickfix window
augroup QFixToggle
 autocmd!
 autocmd BufWinEnter quickfix let g:qfix_win = bufnr("$")
 autocmd BufWinLeave * if exists("g:qfix_win") && expand("<abuf>") == g:qfix_win | unlet! g:qfix_win | endif
augroup END

let g:jah_Quickfix_Win_Height=20
nnoremap <leader><F5> :QFix<CR>

"open cwindow automatically on errors
autocmd QuickFixCmdPost * nested cwindow | redraw!

" }}}
" Plugin Configuration--------------------------------------------------- {{{

" ----------------------------
" Ack - Command-Shift-F on OSX
" ----------------------------

"use with ag with silver searcher
let g:ackprg = 'ag --nogroup --nocolor --column'

map <D-F> :Ack<space>
map <leader>f :Ack<space>


" ---------------
" ctrlp
" ---------------
let g:ctrlp_working_path_mode = 2
nnoremap <silent> <D-t> :CtrlP<CR>

" default command
let g:ctrlp_cmd = 'CtrlPMixed'

let g:ctrlp_custom_ignore = {
      \ 'dir':  '\.git$\|\.hg$\|\.svn$\|cassettes',
      \ 'file': '\.exe$\|\.so$\|\.dll$|\DS_Store$'}

"CtrlP jump extension settings
nnoremap <c-]> :CtrlPtjump<cr>
vnoremap <c-]> :CtrlPtjumpVisual<cr>

" custom file listing command
let g:ctrlp_user_command = 'find %s -type f'

let g:ctrlp_extensions = ['funky']
nnoremap <Leader>fu :CtrlPFunky<Cr>

" narrow the list down with a word under cursor
nnoremap <Leader>fU :execute 'CtrlPFunky ' . expand('<cword>')<Cr>



"------------------
" airline settings
"------------------

" remove separators
let g:airline_left_sep=''
let g:airline_right_sep=''

" set second section to filename
let g:airline_section_c="%t"

" empty fourth section
"let g:airline_section_c=""
let g:airline_section_x=""
 "put filetype in fifth section
let g:airline_section_y="%Y"


" ---------------
"    Fugitive
" ---------------

nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>gc :Gcommit<CR>
nnoremap <silent> <leader>gb :Gblame<CR>
nnoremap <silent> <leader>gl :Glog<CR>
nnoremap <silent> <leader>gp :Git push<CR>
nnoremap <silent> <Leader>gw :Gwrite<CR>
" Mnemonic, gu = Git Update
nnoremap <silent> <Leader>gu :Git pull<CR>
" Exit a diff by closing the diff window
nnoremap <silent> <Leader>gx :wincmd h<CR>:q<CR>

" ---------------
" startify settings
" ---------------

" bookmarks
let g:startify_bookmarks = [ '~/workspace/iAwriter/Log.md', '~/workspace/projects/rails/katikia/Gemfile' ]

" change directory when open a file or bookmark
let g:startify_change_to_dir = 1

" change directory when open a file or bookmark is under git
let g:startify_change_to_vcs_root = 1

let g:startify_files_number= 8

" dont update sessions on close
let g:startify_session_persistence = 0

let g:startify_session_autoload = 1

let g:startify_list_order = [
      \ ['   Bookmarks:'],
      \ 'bookmarks',
      \ ['   LRU:'],
      \ 'files',
      \ ['   sessions:'],
      \ 'sessions'
      \ ]

let g:startify_skiplist = [
      \ 'COMMIT_EDITMSG',
      \ $VIMRUNTIME .'/doc',
      \ 'bundle/.*/doc',
      \ '.vimgolf',
      \ ]
let g:startify_custom_footer =
      \ map(split(system('tips | cowsay `random_quote`' ), '\n'), '"   ". v:val') + ['']

let g:startify_session_dir = '~/.vim/sessions'

hi StartifyBracket ctermfg=240
hi StartifyNumber  ctermfg=215
hi StartifyPath    ctermfg=245
hi StartifySlash   ctermfg=240
hi StartifySpecial ctermfg=240
hi StartifyHeader  ctermfg=114
hi StartifyFooter  ctermfg=240
hi StartifyFile    ctermfg=111

"----------------
"    Gist
"----------------
if executable("pbcopy")
  " The copy command
  let g:gist_clip_command = 'pbcopy'
elseif executable("xclip")
  " The copy command
  let g:gist_clip_command = 'xclip -selection clipboard'
elseif executable("putclip")
  " The copy command
  let g:gist_clip_command = 'putclip'
endif

" detect filetype if vim failed auto-detection.
let g:gist_detect_filetype = 1


"------------------
" Toggle Gundo
"------------------
nmap <C-F1> :GundoToggle<CR>
imap <C-F1> <ESC>:GundoToggle<CR>


"------------------
" NERD Commenter
"------------------
if has("gui_macvim") && has("gui_running")
  map <D-/> <plug>NERDCommenterToggle<CR>j
  imap <D-/> <Esc><plug>NERDCommenterToggre<CR>ji
else
  map <leader>/ <plug>NERDCommenterToggle<CR>j
  inoremap <leader>/ <Esc><plug>NERDCommenterToggle<CR>i
endif


"------------------
" TagBar
"------------------
map <leader>rt :TagbarToggle<CR>


"------------------
" Syntastic
"------------------

" Show sidebar signs.
let g:syntastic_enable_signs=1
let g:syntastic_quiet_warnings=1
let g:syntastic_error_symbol='✗'
let g:syntastic_enable_highlighting = 1

"------------------
" NERD Tree
"------------------

map <leader>n :NERDTreeToggle<CR>
"map <leader>n :NERDTreeToggle %:p:h<CR>

"view the current buffer in NERDTree helpful in tabs
"nmap <leader>nt :NERDTreeFind<CR>

" set the working directory to the current file
"set autochdir
"autocmd BufEnter * lcd %:p:h

"ignore files on NERDTree
let NERDTreeIgnore=['\.pyc$', '\.pyo$', '\.rbc$', '\.rbo$', '\.class$', '\.o$', '\~$']
let NERDTreeIgnore=['\.pyc', '\~$', '\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr']

"show bookmarks
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=0
let NERDTreeQuitOnOpen=1
let NERDTreeShowHidden=0
let NERDTreeKeepTreeInNewTab=1

"---------------
" Sessions
"---------------

" bindings
nnoremap <leader>os :OpenSession<CR>
let g:session_autosave="yes"

"-----------------
"session directory
"-----------------
let g:session_directory="~/.vim/sessions"
let g:session_autosave=0
let g:session_autoload=0

"---------------
" Buffergator
" --------------
let g:buffergator_autoexpand_on_split = 0


"------------------
"   Snipmate
"------------------
" Source support_function.vim to support snipmate-snippets.
"if filereadable(expand("~/.vim/bundle/snipmate-snippets/snippets/support_functions.vim"))
  "source ~/.vim/bundle/snipmate-snippets/snippets/support_functions.vim
"endif


"---------------------
" OmniComplete
"---------------------

if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
        \if &omnifunc == "" |
        \setlocal omnifunc=syntaxcomplete#Complete |
        \endif
endif


" Enable omni completion. Not required if they are already set elsewhere in .vimrc
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS


"--------------------------
" ctags
"---------------------------
set tags=./.git/tags;./tags;/
set tags+=~/dotfiles/vim/tags/ruby_and_gems

"---------------
"Run Ruby files
"---------------

let g:RubyRunner_open_below = 1
"let g:RubyRunner_keep_focus_key = '<Leader>R'
if has("gui_macvim")
  let g:RubyRunner_key = '<D-r>'
  let g:RubyRunner_keep_focus_key = '<D-R>'
end


" Run ruby inline
autocmd FileType ruby nmap <buffer> <M-m> <Plug>(xmpfilter-mark)
autocmd FileType ruby xmap <buffer> <M-m> <Plug>(xmpfilter-mark)
autocmd FileType ruby imap <buffer> <M-m> <Plug>(xmpfilter-mark)

autocmd FileType ruby nmap <buffer> <M-r> <Plug>(xmpfilter-run)
autocmd FileType ruby xmap <buffer> <M-r> <Plug>(xmpfilter-run)
autocmd FileType ruby imap <buffer> <M-r> <Plug>(xmpfilter-run)

" vim-ruby-doc
let g:ruby_doc_ruby_host = 'http://docs.dev/search/-rubydocs?q='
let g:ruby_doc_rails_host='http://docs.dev/search/-railsdocs?q='

"--------------------------
" Autoclose Tag
"---------------------------
au FileType xhtml,xml ru ftplugin/html/autoclosetag.vim
nmap <Leader>ac <Plug>ToggleAutoCloseMappings


" Ruby Documentation Tools
let g:ruby_doc_command='open'

"
" change background by sunset
let g:sunset_latitude = 39.42
let g:sunset_longitude = 20.47
let g:sunset_utc_offset = 2 "Athens

"-------
" Vroom
"-------

let g:vroom_use_dispatch=1

" }}}
" cocoa plugins settings {{{

"clang_complete
"most stuff taken from here http://appventure.me/2013/01/use-vim-as-xcode-alternative-ios-mac-cocoa.html

" Disable auto completion, always <c-x> <c-o> to complete
let g:clang_complete_auto = 0
let g:clang_use_library = 1
let g:clang_periodic_quickfix = 0
let g:clang_close_preview = 1

" For Objective-C, this needs to be active, otherwise multi-parameter methods won't be completed correctly
let g:clang_snippets = 1

let g:clang_snippets_engine = 'ultisnips'

let g:clang_exec = '/usr/local/bin/clang'
let g:clang_library_path = '/usr/local/lib/libclang.dylib'

" Read the clang complete file
let g:syntastic_objc_config_file = '.clang_complete'

nnoremap <silent> ` :Errors<CR>

" Tell it to use clang instead of gcc
let g:syntastic_objc_compiler = 'clang'
let g:syntastic_objc_checkers = ['clang']
"}}}
"Functions----------------------------------------------------------------------- {{{

function! s:setupWrapping()
  set wrap
  set linebreak
  set textwidth=72
  set nolist
endfunction

"-------------------------
" Delete inactive buffers
"-------------------------
function! DeleteInactiveBufs()
  "From tabpagebuflist() help, get a list of all buffers in all tabs
  let tablist = []
  for i in range(tabpagenr('$'))
    call extend(tablist, tabpagebuflist(i + 1))
  endfor

  "Below originally inspired by Hara Krishna Dara and Keith Roberts
  "http://tech.groups.yahoo.com/group/vim/message/56425
  let nWipeouts = 0
  for i in range(1, bufnr('$'))
    if bufexists(i) && !getbufvar(i,"&mod") && index(tablist, i) == -1
      "bufno exists AND isn't modified AND isn't in the list of buffers open in windows and tabs
      silent exec 'bwipeout' i
      let nWipeouts = nWipeouts + 1
    endif
  endfor
  echomsg nWipeouts . ' buffer(s) wiped out'
endfunction
command! Bdi :call DeleteInactiveBufs()

"---------------------
" highlight cursoline
"---------------------

function! CursorPing()
  set cursorline cursorcolumn
  redraw
  sleep 150m
  set nocursorline nocursorcolumn
endfunction

nmap <leader>sc :call CursorPing()<CR>
map <silent> <Leader>cl :set cursorline! <CR>
map <silent> <Leader>cn :set nocursorcolumn nocursorline <CR>

"------------------------------------------------------------------
" This is how i execute ruby tests in terminal when i code on macvim
" see more on this blog post
"------------------------------------------------------------------

" copy to clipboard current path
noremap <silent> <leader>g :let @+=expand("%:p")<CR>

" append to clipboard current path and cursor line number
function! PathAndLineNum()
  :let @+=expand("%:p")
  :let @+ .=":"
  :let @+ .=line(".")
endfunction

" keyboard maestro support
noremap <leader>G :call PathAndLineNum()<CR>


"-------------------------------
" open urls to browsers
" open vundles from github
" [] fix it for local html files
"-------------------------------

ruby <<EOF
  def my_open_uri
    re = %r{https?:\/\/[\S]+}
    vundles_regx = %r{"?(\S+)\s'(\S+)'}
    line = VIM::Buffer.current.line
    m = line.match(vundles_regx)

    if url = line[re]
      system("open", url)
      VIM::message(url)
    elsif m && m[1] == "Bundle"
      system("open", "http://github.com/" + m[2].to_s)
      VIM::message(url)
    elsif m && m[1] == "gem"
      system("open", "https://rubygems.org/gems/" + m[2].to_s)
      VIM::message(url)
    else
      VIM::message("No URI found in line.")
    end
  end
EOF

if !exists("*OpenURI")
  function! OpenURI()
    :ruby my_open_uri
  endfunction
endif
nnoremap <Leader>wf :call OpenURI()<CR><CR>


"---------------------------
"google search current line
"---------------------------
ruby <<EOF
  def search_google
    query = VIM::Buffer.current.line
    system("open", "http://google.com/search?q=#{query}")
  end
EOF
function! SearchGoogle()
  :ruby search_google
endfunction
nnoremap <Leader>we :call SearchGoogle()<CR><CR>

" Documentation via Dash
" [ ] extract it to a plugin

function! DashDocsSearch()
  let current_word = '<cword>'
  :redir => output
  :set filetype
  :redir END
  let match_filetype = matchlist(output, 'filetype=\(\S\+\)')
  let ftype = ''
  if len(match_filetype) > 1
    let ftype = match_filetype[1]
  endif
  let command = 'open dash://'.ftype . ":" .current_word
  call s:execute(command)
endfunction

function! s:execute(cmd)
  let cmd = a:cmd
  if !has("gui_running")
    silent exe '!'.cmd.' &> /dev/null'
    exec ':redraw!'
  else
    exe '!'.cmd.' &> /dev/null &'
  endif
  return v:shell_error
endfunction

nnoremap <Leader>dc :call DashDocsSearch()<cr><cr>

function! SearchDashDocs()
  !open dash://<cword>
endfunction

nnoremap <Leader>dC :call SearchDashDocs()<cr>

" Dash plugin settings
nmap <silent> <leader>d <Plug>DashSearch
nmap <silent> <leader>D <Plug>DashGlobalSearch

let g:dash_map = {
      \ 'ruby'       : 'ruby',
      \ 'coffee'     : 'coffeescript',
      \ 'javascript' : 'backbone',
      \ 'elixir'     : 'elixir',
      \ 'clojure'    : 'clojure'
      \ }


" Thumbnail plugin setting
noremap <Leader>m :Thumbnail<cr>

"CtrlPFunky settings
"Jump to function via ctrlp.vim interface

let g:ctrlp_extensions = ['funky']
nnoremap <Leader>fu :CtrlPFunky<Cr>

" narrow the list down with a word under cursor
nnoremap <Leader>fU :execute 'CtrlPFunky ' . expand('<cword>')<Cr>

let g:ctrlp_funky_ruby_requires = 1
let g:ctrlp_funky_ruby_classes = 1
let g:ctrlp_funky_ruby_modules = 1

" }}}
" Programming Languages--------------------------------------------------- {{{
" Ruby {{{

" around block ruby
" text object for ruby blocks
" http://vimcasts.org/blog/2010/12/a-text-object-for-ruby-blocks/
" text object for ruby blocks
" https://github.com/kana/vim-textobj-user
if has("autocmd")
  filetype indent plugin on
endif
runtime macros/matchit.vim      "Also require the matchit.vim

au BufRead,BufNewFile *.rb setlocal tags+=~/.vim/tags/ruby_tags
au BufRead,BufNewFile *.rb setlocal tags+=~/.vim/tags/ruby_and_gems
" }}}
" rails helps-----------------------{{{

"projections
let g:rails_projections = {
      \ "config/projections.json": {
      \   "command": "projections"
      \ },
      \ "spec/features/*_spec.rb": {
      \   "command": "feature",
      \   "template": "require 'spec_helper'\n\nfeature '%h' do\n\nend",
      \ },
      \ "config/*.rb": { "command": "config"  },
      \ "test/factories/*.rb": {
      \   "command":   "factory",
      \   "affinity":  "collection",
      \   "alternate": "app/models/%i.rb",
      \   "related":   "db/schema.rb#%s",
      \   "test":      "test/models/%i_test.rb",
      \   "template":  "FactoryGirl.define do\n  factory :%i do\n  end\nend",
      \   "keywords":  "factory sequence"
      \ },
      \ "spec/factories/*.rb": {
      \   "command":   "factory",
      \   "affinity":  "collection",
      \   "alternate": "app/models/%i.rb",
      \   "related":   "db/schema.rb#%s",
      \   "test":      "spec/models/%i_test.rb",
      \   "template":  "FactoryGirl.define do\n  factory :%i do\n  end\nend",
      \   "keywords":  "factory sequence"
      \ },
      \ "app/uploaders/*_uploader.rb": {
      \   "command": "uploader",
      \   "template":
      \   "class %SUploader < CarrierWave::Uploader::Base\nend"
      \   },
      \ "app/decorators/*_decorator.rb": {
      \   "command": "decorator",
      \   "affinity": "model",
      \   "test": "spec/decorators/%s_spec.rb",
      \   "related": "app/models/%s.rb",
      \   "template": "class %SDecorator < Draper::Decorator\nend"
      \  }
      \}
" }}}
" Clojure {{{

"clojure rainbow support
let g:vimclojure#HighlightBuiltins = 1
let g:vimclojure#ParenRainbow = 1

au Syntax clojure RainbowParenthesesLoadRound
au Syntax clojure RainbowParenthesesLoadRound
au Syntax clojure RainbowParenthesesLoadBraces
au Syntax clojure RainbowParenthesesLoadSquare
au Syntax clojure RainbowParenthesesLoadChevrons

autocmd BufEnter *.clj RainbowParenthesesToggle
autocmd BufLeave *.clj RainbowParenthesesToggle

" }}}
"coffeescript {{{

"Fold by indentation
au BufNewFile,BufReadPost *.coffee setl foldmethod=indent

"Two-space indentation
au BufNewFile,BufReadPost *.coffee setl shiftwidth=2 expandtab

"Run coffee files
autocmd FileType coffee noremap<D-r> <ESC>:CoffeeRun %<cr>
autocmd FileType coffee inoremap<D-r> :CoffeeRun %<cr>

" Ctags settings for coffeescript
let g:tlist_coffee_settings = 'coffee;f:function;v:variable,c:class'

"Compile to javascript in a vertical buffer
let coffee_compile_vert = 1

" }}}
"javascript {{{

let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
" }}}
" elixir {{{

autocmd FileType elixir noremap<D-r> :!elixir %<cr>

" }}}
" }}}

hi NonText guifg=bg guibg=bg
